site_name: Recettes Gervais
site_url: https://giem-git.github.io/recettes/
repo_url: https://github.com/giem-git/recipes
edit_uri: edit/main/docs/

nav:
  - Home: index.md

theme:
  name : material
  icon:
    logo: material/food-takeout-box-outline
    edit: material/pencil
    view: material/eye
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
      primary: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
      primary: blue grey
  features:
    #- navigation.tabs
    #- navigation.top
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - header.autohide
    - content.action.edit


extra:
  generator: false

